# Auto-generated by rake rpt:export:fng[2] on 2025-09-04 23:23:06 UTC
# Company ID: 2 (Fondo Nacional de garantias)
# This script creates/updates Dimensions and CorporateGoals by matching Period by name within the company.

company = Company.find_by!(id: 2)

# Cleanup existing data for this company (delete CorporateGoals first, then Dimensions)
company.periods.find_each do |p|
  CorporateGoal.where(period: p).delete_all
end
company.periods.find_each do |p|
  Dimension.where(period: p).delete_all
end

def find_period!(company, name)
  p = company.periods.find_by(name: name)
  raise "Period not found for company #{company.id} with name '#{name}'" unless p
  p
end

# Dimensions
begin
  period = find_period!(company, '2025')
  Dimension.find_or_create_by!(period: period, name: 'Dimensión Comercial & Social')
rescue => e
  puts "Dimension 'Dimensión Comercial & Social' skipped: #{e.message}"
end


begin
  period = find_period!(company, '2025')
  Dimension.find_or_create_by!(period: period, name: 'Dimensión Financiera')
rescue => e
  puts "Dimension 'Dimensión Financiera' skipped: #{e.message}"
end


begin
  period = find_period!(company, '2025')
  Dimension.find_or_create_by!(period: period, name: 'Dimensión Gestión Integral & Tecnología')
rescue => e
  puts "Dimension 'Dimensión Gestión Integral & Tecnología' skipped: #{e.message}"
end


begin
  period = find_period!(company, '2025')
  Dimension.find_or_create_by!(period: period, name: 'Dimensión Aprendizaje y crecimiento')
rescue => e
  puts "Dimension 'Dimensión Aprendizaje y crecimiento' skipped: #{e.message}"
end


# CorporateGoals
begin
  period = find_period!(company, '2025')
  dimension = Dimension.find_by!(period: period, name: 'Dimensión Aprendizaje y crecimiento')
  cg = CorporateGoal.where(period: period, dimension: dimension, description: 'Posicionar la imagen del FNG como apalancador de acceso a crédito').first_or_initialize
  cg.percentage = 15.0
  cg.score = 99.1
  cg.goal = 'Posicionamiento'
  cg.goal_floor = 7.0
  cg.goal_value = 11.0
  cg.goal_ceil = 13.0
  cg.goal_achieved = 10.0
  cg.formula_below_value = '-0.0059 * (x**2) + 0.1291 * x + 0.29'
  cg.formula_above_value = '0.0173 * (x**2) - 0.3675 * x + 2.9561'
  cg.save!
rescue => e
  puts "CorporateGoal 'Posicionar la imagen del FNG como apalancador de acceso a crédito' skipped: #{e.message}"
end


begin
  period = find_period!(company, '2025')
  dimension = Dimension.find_by!(period: period, name: 'Dimensión Comercial & Social')
  cg = CorporateGoal.where(period: period, dimension: dimension, description: 'Movilización de créditos – número de créditos
').first_or_initialize
  cg.percentage = 25.0
  cg.score = 87.68
  cg.goal = 'Número de creditos'
  cg.goal_floor = 675000.0
  cg.goal_value = 725000.0
  cg.goal_ceil = 797500.0
  cg.goal_achieved = 682500.0
  cg.formula_below_value = '-4.0e-11 * (x**2) + 6.0e-5 * x - 21.441'
  cg.formula_above_value = '2.0 * (10**-11) * (x**2) - 2.0 * (10**-5) * x + 9.0648'
  cg.save!
rescue => e
  puts "CorporateGoal 'Movilización de créditos – número de créditos
' skipped: #{e.message}"
end


begin
  period = find_period!(company, '2025')
  dimension = Dimension.find_by!(period: period, name: 'Dimensión Financiera')
  cg = CorporateGoal.where(period: period, dimension: dimension, description: 'Utilidad antes de impuestos + bonificación
').first_or_initialize
  cg.percentage = 20.0
  cg.score = 95.7
  cg.goal = 'Utilidad'
  cg.goal_floor = 95.61
  cg.goal_value = 106.24
  cg.goal_ceil = 116.86
  cg.goal_achieved = 96.0
  cg.formula_below_value = '(0.0042 * x) + 0.5538'
  cg.formula_above_value = '0.4345 * Math.exp(0.0079 * x)'
  cg.save!
rescue => e
  puts "CorporateGoal 'Utilidad antes de impuestos + bonificación
' skipped: #{e.message}"
end


begin
  period = find_period!(company, '2025')
  dimension = Dimension.find_by!(period: period, name: 'Dimensión Comercial & Social')
  cg = CorporateGoal.where(period: period, dimension: dimension, description: 'Movilización de créditos – meta de colocación').first_or_initialize
  cg.percentage = 20.0
  cg.score = 109.52
  cg.goal = 'Movilización de créditos – meta de colocación'
  cg.goal_floor = 20.5
  cg.goal_value = 23.5
  cg.goal_ceil = 25.85
  cg.goal_achieved = 25.84
  cg.formula_below_value = '(-0.0086 * x * x) + (0.4176 * x) - 4.0637'
  cg.formula_above_value = '(0.0098 * x * x) - (0.4428 * x) + 5.9936'
  cg.save!
rescue => e
  puts "CorporateGoal 'Movilización de créditos – meta de colocación' skipped: #{e.message}"
end


begin
  period = find_period!(company, '2025')
  dimension = Dimension.find_by!(period: period, name: 'Dimensión Gestión Integral & Tecnología')
  cg = CorporateGoal.where(period: period, dimension: dimension, description: 'Proyectos de transformación e innovación implementados').first_or_initialize
  cg.percentage = 20.0
  cg.score = 75.0
  cg.goal = 'Proyectos de transformación e innovación implementados'
  cg.goal_floor = 5.0
  cg.goal_value = 9.0
  cg.goal_ceil = 10.0
  cg.goal_achieved = 8.0
  cg.formula_below_value = '(goal_achieved - goal_floor) / (goal_value - goal_floor)'
  cg.formula_above_value = '(goal_achieved - goal_floor) / (goal_value - goal_floor)'
  cg.save!
rescue => e
  puts "CorporateGoal 'Proyectos de transformación e innovación implementados' skipped: #{e.message}"
end

