# frozen_string_literal: true

namespace :export do
  desc "Export Dimensions and CorporateGoals for a company (default COMPANY_ID=2) to db/seeds/fng.seeds.rb"
  task fng: :environment do
    company_id = (ENV['COMPANY_ID'] || '2').to_i
    company = Company.find_by(id: company_id)
    abort "Company with id=#{company_id} not found" unless company

    periods = company.periods.includes(dimensions: :corporate_goals)

    data = {
      company_id: company_id,
      periods: periods.map do |p|
        {
          name: p.name,
          period_type: p.period_type,
          status: p.status,
          company_profit_percentage: p.company_profit_percentage&.to_f,
          minimum_score_area_goals: p.minimum_score_area_goals&.to_f,
          minimum_score_corporate_goals: p.minimum_score_corporate_goals&.to_f,
          minimum_score_employee: p.minimum_score_employee&.to_f,
          minimum_score_position_goals: p.minimum_score_position_goals&.to_f,
          dimensions: p.dimensions.map do |d|
            {
              name: d.name,
              corporate_goals: CorporateGoal.where(period_id: p.id, dimension_id: d.id).map do |g|
                {
                  description: g.description,
                  percentage: g.percentage&.to_f,
                  score: g.score&.to_f,
                  goal: g.goal,
                  goal_floor: g.goal_floor&.to_f,
                  goal_value: g.goal_value&.to_f,
                  goal_ceil: g.goal_ceil&.to_f,
                  goal_achieved: g.goal_achieved&.to_f,
                  formula_below_value: g.formula_below_value,
                  formula_above_value: g.formula_above_value
                }
              end
            }
          end
        }
      end
    }

    require 'json'
    json = JSON.pretty_generate(data)
    seed_path = Rails.root.join('db', 'seeds', 'fng.seeds.rb')

    File.open(seed_path, 'w') do |f|
      f.puts "# frozen_string_literal: true"
      f.puts "# Auto-generated by rake export:fng at #{Time.now.utc}"
      f.puts "require 'json'"
      f.puts "DATA_JSON = <<~JSON"
      f.puts json
      f.puts "JSON"
      f.puts
      f.puts "data = JSON.parse(DATA_JSON)"
      f.puts "ActiveRecord::Base.transaction do"
      f.puts "  company_id = data['company_id']"
      f.puts "  data['periods'].each do |p|"
      f.puts "    period = Period.find_or_initialize_by(company_id: company_id, name: p['name'])"
      f.puts "    period.assign_attributes(p.slice('period_type','status','company_profit_percentage','minimum_score_area_goals','minimum_score_corporate_goals','minimum_score_employee','minimum_score_position_goals'))"
      f.puts "    period.save!"
      f.puts "    p['dimensions'].each do |d|"
      f.puts "      dim = Dimension.find_or_initialize_by(period_id: period.id, name: d['name'])"
      f.puts "      dim.save!"
      f.puts "      d['corporate_goals'].each do |cg|"
      f.puts "        goal = CorporateGoal.find_or_initialize_by(period_id: period.id, dimension_id: dim.id, description: cg['description'])"
      f.puts "        goal.assign_attributes(cg.slice('percentage','goal','goal_floor','goal_value','goal_ceil','goal_achieved','formula_below_value','formula_above_value'))"
      f.puts "        goal.save!"
      f.puts "      end"
      f.puts "    end"
      f.puts "  end"
      f.puts "end"
    end

    puts "Exported #{periods.size} periods, #{periods.sum { |p| p.dimensions.size }} dimensions, and #{periods.sum { |p| CorporateGoal.where(period_id: p.id).count }} corporate goals to #{seed_path}"
  end
end
