# frozen_string_literal: true

require 'fileutils'

namespace :rpt do
  namespace :export do
    desc 'Export Dimensions and CorporateGoals for a company into db/seeds/fng.seeds.rb. Usage: rake "rpt:export:fng[COMPANY_ID]"'
    task :fng, [:company_id] => :environment do |_t, args|
      company_id = args[:company_id].to_i
      abort 'Please provide a valid company_id' if company_id <= 0

      company = Company.find_by(id: company_id)
      abort "Company not found with id=#{company_id}" unless company

      periods = company.periods
      period_ids = periods.select(:id)

      dimensions = Dimension.where(period_id: period_ids).includes(:period)
      goals = CorporateGoal.where(period_id: period_ids).includes(:period, :dimension)

      # Build static content for the seed file
      dim_entries = dimensions.map do |d|
        pn = d.period.name.to_s.gsub("'", "\\'")
        dn = d.name.to_s.gsub("'", "\\'")
        template = <<-'ENTRY'
begin
  period = find_period!(company, '%{pn}')
  Dimension.find_or_create_by!(period: period, name: '%{dn}')
rescue => e
  puts "Dimension '%{dn}' skipped: #{e.message}"
end
ENTRY
        template % { pn: pn, dn: dn }
      end

      goal_entries = goals.map do |g|
        pn = g.period.name.to_s.gsub("'", "\\'")
        dn = g.dimension.name.to_s.gsub("'", "\\'")
        desc = g.description.to_s.gsub("'", "\\'")
        goal = g.goal.to_s.gsub("'", "\\'")
        fb = g.formula_below_value.to_s.gsub("'", "\\'")
        fa = g.formula_above_value.to_s.gsub("'", "\\'")
        percentage = g.percentage.nil? ? 'nil' : g.percentage.to_f.round(2)
        score = g.score.nil? ? 'nil' : g.score.to_f.round(2)
        goal_floor = g.goal_floor.nil? ? 'nil' : g.goal_floor.to_f
        goal_value = g.goal_value.nil? ? 'nil' : g.goal_value.to_f
        goal_ceil = g.goal_ceil.nil? ? 'nil' : g.goal_ceil.to_f
        goal_achieved = g.goal_achieved.nil? ? 'nil' : g.goal_achieved.to_f
        template = <<-'ENTRY'
begin
  period = find_period!(company, '%{pn}')
  dimension = Dimension.find_by!(period: period, name: '%{dn}')
  cg = CorporateGoal.where(period: period, dimension: dimension, description: '%{desc}').first_or_initialize
  cg.percentage = %{percentage}
  cg.score = %{score}
  cg.goal = '%{goal}'
  cg.goal_floor = %{goal_floor}
  cg.goal_value = %{goal_value}
  cg.goal_ceil = %{goal_ceil}
  cg.goal_achieved = %{goal_achieved}
  cg.formula_below_value = '%{fb}'
  cg.formula_above_value = '%{fa}'
  cg.save!
rescue => e
  puts "CorporateGoal '%{desc}' skipped: #{e.message}"
end
ENTRY
        template % {
          pn: pn,
          dn: dn,
          desc: desc,
          goal: goal,
          fb: fb,
          fa: fa,
          percentage: percentage,
          score: score,
          goal_floor: goal_floor,
          goal_value: goal_value,
          goal_ceil: goal_ceil,
          goal_achieved: goal_achieved
        }
      end

      outer = <<-'RUBY'
# Auto-generated by rake rpt:export:fng[%{company_id}] on %{timestamp}
# Company ID: %{company_id} (%{company_name})
# This script creates/updates Dimensions and CorporateGoals by matching Period by name within the company.

company = Company.find_by!(id: %{company_id})

def find_period!(company, name)
  p = company.periods.find_by(name: name)
  raise "Period not found for company #{company.id} with name '#{name}'" unless p
  p
end

# Dimensions
%{dimensions}

# CorporateGoals
%{goals}
RUBY

      content = outer % {
        company_id: company.id,
        company_name: company.name.to_s.gsub("%", "%%"),
        timestamp: Time.now.utc,
        dimensions: dim_entries.join("\n\n"),
        goals: goal_entries.join("\n\n")
      }

      FileUtils.mkdir_p(Rails.root.join('db', 'seeds'))
      path = Rails.root.join('db', 'seeds', 'fng.seeds.rb')
      File.write(path, content)
      puts "Exported to #{path}"
    end
  end
end
